import { Container } from 'react-bootstrap';
import { Link } from 'react-router-dom';

export function AboutPage() {
  return (
    <Container style={{ maxWidth: '80%' }} className="text-start pt-4">
      <p> Happy Stitch is an open source cross stitch pattern generator that lets users: </p>
      <ul>
        <li>Create patterns from scratch</li>
        <li>Upload an image to convert to a pattern</li>
        <li>Edit already created paterns</li>
      </ul>
      <p>
        Patterns generated by this software are not currently compatible with Saga or other pattern
        tracking software, but hopefully will be in the future
      </p>
      <p>
        {' '}
        This software has been created as a just-for-fun project. Efforts have been made to make the
        pattern generation and colour matching as accurate as possible, but please double check your
        colours before you start stitching!
      </p>
      <p>
        {' '}
        The colour scheme and theming for this site was decided by our 3 year old daughter, who is
        very much enjoying her pink/purple/unicorn/princesses phase.
      </p>
    </Container>
  );
}
